### ISSUE TITLE
Does it have to be .svg?

### ISSUE THREAD

**Issue by dragonfire1119** [lucidlemon/paradeiser#8]
Can I use fontawesome for the icons or is that possible? I've tried and it renders them really small.

**Comment by lucidlemon** [comment]
The font is really small as the place for icons may be used for text as well, as seen in demo/demo3.html, if you want to user your fontawesome package just define your font size for `.paradeiser .paradeiser_icon_canvas`like this:

``` css
.paradeiser .paradeiser_icon_canvas{
  font-size: 24px;
}
```

hope this helps
